#!/bin/bash

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../Release:/usr/local/lib/
export DYLD_LIBRARY_PATH=Release:/usr/local/share/tbb40_20120613oss/lib/:/usr/local/lib/
export ARCHFLAGS="-arch x86_64"
python setup.py build_ext --inplace
python PyChannelBasisTest.py
